// Mock/Demo data for Prem MCX Trading Academy - eCommerce Version
import type { MoodleCourse, MoodleSiteInfo } from '@/types/moodle';

export const demoSiteInfo: MoodleSiteInfo = {
  sitename: 'Prem MCX Trading Academy',
  username: 'trader',
  firstname: 'Professional',
  lastname: 'Trader',
  fullname: 'Professional Trader',
  userid: 1,
  siteurl: 'https://premmcx.academy',
  userpictureurl: '',
};

export const demoCourses: MoodleCourse[] = [
  {
    id: 1,
    shortname: 'MCX-BASIC-ADV',
    fullname: 'Trade with Experts: Basic to Advance Morning Setup Course',
    summary: 'Master MCX trading from basics to advanced strategies. Live classes with morning market setups, real-time trade analysis, and expert mentorship. Perfect for beginners and intermediate traders.',
    visible: 1,
    format: 'topics',
    enrolledusercount: 456,
    price: 13499,
    courseType: 'LIVE CLASS',
    categoryName: 'Basic',
    isFeatured: true,
    isPopular: true,
    startdate: Date.now() / 1000,
  },
  {
    id: 2,
    shortname: 'LIVE-MENTOR',
    fullname: 'Live Mentorship Batch - Professional Trading',
    summary: 'Exclusive live mentorship program with daily market analysis, trade setups, and personalized guidance from professional traders. Limited seats available.',
    visible: 1,
    format: 'topics',
    enrolledusercount: 189,
    price: 4999,
    courseType: 'MENTORSHIP',
    categoryName: 'Advanced',
    isFeatured: true,
    isPopular: true,
    startdate: Date.now() / 1000,
  },
  {
    id: 3,
    shortname: 'BANKNIFTY-CLOSING',
    fullname: 'Bank Nifty Closing Day Setup Course',
    summary: 'Learn profitable Bank Nifty closing strategies, expiry day trading tactics, and options premium collection techniques. Includes recorded sessions and strategy PDFs.',
    visible: 1,
    format: 'topics',
    enrolledusercount: 298,
    price: 999,
    originalPrice: 3100,
    discountPercent: 67,
    courseType: 'VIDEOS',
    categoryName: 'Options Trading',
    isFeatured: true,
    startdate: Date.now() / 1000,
  },
  {
    id: 4,
    shortname: 'OPTIONS-BUYING',
    fullname: 'Option Buying Setup 2 - For Beginners',
    summary: 'Complete options buying course for beginners. Learn entry/exit strategies, strike selection, and timing. Live classes with practical examples and trade setups.',
    visible: 1,
    format: 'topics',
    enrolledusercount: 367,
    price: 6999,
    originalPrice: 9999,
    discountPercent: 30,
    courseType: 'LIVE CLASS',
    categoryName: 'Options Trading',
    isPopular: true,
    hasLimitedOffer: true,
    startdate: Date.now() / 1000,
  },
  {
    id: 5,
    shortname: 'SCALPING-PRO',
    fullname: 'Trade with Experts: Scalping Course',
    summary: 'Master 1-5 minute scalping strategies for quick profits. Live trading sessions showing real scalps, risk management, and psychology of scalping.',
    visible: 1,
    format: 'topics',
    enrolledusercount: 423,
    price: 4999,
    originalPrice: 5999,
    discountPercent: 16,
    courseType: 'LIVE CLASS',
    categoryName: 'Scalping',
    isPopular: true,
    hasLimitedOffer: true,
    startdate: Date.now() / 1000,
  },
  {
    id: 6,
    shortname: 'MCX-BASIC',
    fullname: 'Trade with Experts: Basic Course',
    summary: 'Foundation course for MCX commodity trading. Learn market basics, chart reading, and simple strategies to start your trading journey confidently.',
    visible: 1,
    format: 'topics',
    enrolledusercount: 589,
    price: 2149,
    courseType: 'LIVE CLASS',
    categoryName: 'Basic',
    isFeatured: true,
    startdate: Date.now() / 1000,
  },
  {
    id: 7,
    shortname: 'ALL-IN-ONE',
    fullname: 'All in One Master Course - Complete Trading Package',
    summary: 'Comprehensive package including all courses, strategies, and lifetime mentorship. Everything you need to become a professional trader. Best value package.',
    visible: 1,
    format: 'topics',
    enrolledusercount: 145,
    price: 38000,
    courseType: 'MENTORSHIP',
    categoryName: 'Advanced',
    isFeatured: true,
    startdate: Date.now() / 1000,
  },
  {
    id: 8,
    shortname: 'TECH-ANALYSIS-ADV',
    fullname: 'Advanced Technical Analysis Mastery',
    summary: 'Deep dive into advanced indicators, price action, and chart patterns. Recorded video course with weekly live doubt clearing sessions.',
    visible: 1,
    format: 'topics',
    enrolledusercount: 512,
    price: 4999,
    courseType: 'VIDEOS',
    categoryName: 'Technical Analysis',
    isPopular: true,
    startdate: Date.now() / 1000,
  },
  {
    id: 9,
    shortname: 'INTRADAY-STRATEGIES',
    fullname: 'Intraday Trading Strategies - Professional Level',
    summary: 'Learn proven intraday strategies for consistent profits. Includes momentum trading, breakout strategies, and range trading techniques.',
    visible: 1,
    format: 'topics',
    enrolledusercount: 378,
    price: 5499,
    courseType: 'VIDEOS',
    categoryName: 'Intraday',
    startdate: Date.now() / 1000,
  },
  {
    id: 10,
    shortname: 'RISK-MANAGEMENT-PRO',
    fullname: 'Risk Management & Psychology - Professional Trader',
    summary: 'Master risk management, position sizing, and trading psychology. Essential skills for long-term trading success and capital protection.',
    visible: 1,
    format: 'topics',
    enrolledusercount: 445,
    price: 3499,
    courseType: 'VIDEOS',
    categoryName: 'Risk Management',
    isFeatured: true,
    startdate: Date.now() / 1000,
  },
];

export function isMoodleConfigured(): boolean {
  return !!(process.env.MOODLE_URL && process.env.MOODLE_TOKEN);
}
