'use client';

import React, { useEffect, useState, Suspense } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import Navbar from '@/components/Navbar';

interface ReceiptData {
  orderId: string;
  paymentId: string;
  date: string;
  subtotal: number;
  gst: number;
  total: number;
  courses: Array<{ id: number; name: string; price: number }>;
  userEmail: string;
  userName: string;
  status: 'completed' | 'pending' | 'failed';
  razorpaySignature: string;
}

function PaymentReceiptContent() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [receiptData, setReceiptData] = useState<ReceiptData | null>(null);

  useEffect(() => {
    const fetchReceiptData = async () => {
      try {
        const orderId = searchParams.get('orderId');
        const paymentId = searchParams.get('paymentId');

        if (!orderId || !paymentId) {
          setError('Invalid receipt parameters');
          setLoading(false);
          return;
        }

        // Fetch receipt details from backend
        const response = await fetch(`/api/payment/receipt?orderId=${orderId}&paymentId=${paymentId}`);

        if (!response.ok) {
          throw new Error('Failed to fetch receipt');
        }

        const data = await response.json();
        setReceiptData(data);
      } catch (err) {
        const message = err instanceof Error ? err.message : 'Error loading receipt';
        setError(message);
      } finally {
        setLoading(false);
      }
    };

    fetchReceiptData();
  }, [searchParams]);

  const printReceipt = () => {
    window.print();
  };

  const downloadReceipt = () => {
    if (!receiptData) return;

    const receiptContent = `
╔════════════════════════════════════════════════════════════════╗
║                    PAYMENT RECEIPT                             ║
║               Prem MCX Training Academy                        ║
╚════════════════════════════════════════════════════════════════╝

TRANSACTION DETAILS
═══════════════════════════════════════════════════════════════
Order ID:              ${receiptData.orderId}
Payment ID:            ${receiptData.paymentId}
Date & Time:           ${receiptData.date}
Status:                ${receiptData.status.toUpperCase()}

PAYER INFORMATION
═══════════════════════════════════════════════════════════════
Name:                  ${receiptData.userName}
Email:                 ${receiptData.userEmail}

COURSE DETAILS
═══════════════════════════════════════════════════════════════
${receiptData.courses.map((course) => `${course.name} (Course ID: ${course.id})     ₹${course.price.toLocaleString()}`).join('\n')}

PAYMENT BREAKDOWN
═══════════════════════════════════════════════════════════════
Subtotal:              ₹${receiptData.subtotal.toLocaleString('en-IN')}
SGST (9%):             ₹${(receiptData.subtotal * 0.09).toLocaleString('en-IN', { maximumFractionDigits: 0 })}
CGST (9%):             ₹${(receiptData.subtotal * 0.09).toLocaleString('en-IN', { maximumFractionDigits: 0 })}
─────────────────────────────────────────────────────────────
Total GST (18%):       ₹${receiptData.gst.toLocaleString('en-IN')}
═══════════════════════════════════════════════════════════════
TOTAL AMOUNT PAID:     ₹${receiptData.total.toLocaleString('en-IN')}

NOTES
═══════════════════════════════════════════════════════════════
• Payment verified with Razorpay
• Instant enrollment in all purchased courses
• Receipt issued on ${receiptData.date}
• For assistance, contact: support@premmcxtraining.com

Generated by Prem MCX Training Academy
`;

    const blob = new Blob([receiptContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `receipt-${receiptData.orderId}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50">
        <Navbar />
        <div className="flex items-center justify-center h-96">
          <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-500"></div>
        </div>
      </div>
    );
  }

  if (error || !receiptData) {
    return (
      <div className="min-h-screen bg-gray-50">
        <Navbar />
        <div className="max-w-4xl mx-auto px-4 py-12">
          <div className="bg-white rounded-lg shadow-lg p-8">
            <div className="flex items-center gap-4 mb-6">
              <div className="text-4xl">⚠️</div>
              <div>
                <h1 className="text-2xl font-bold text-gray-900">Receipt Not Found</h1>
                <p className="text-gray-600">{error || 'Unable to load receipt details'}</p>
              </div>
            </div>
            <Link href="/my-courses" className="text-blue-600 hover:text-blue-700 font-semibold">
              ← Back to My Courses
            </Link>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />

      <div className="max-w-4xl mx-auto px-4 py-12">
        {/* Success Banner */}
        <div className="mb-8 p-6 bg-green-50 border-2 border-green-200 rounded-lg">
          <div className="flex items-center gap-4">
            <div className="flex-shrink-0">
              <svg className="h-12 w-12 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <div>
              <h1 className="text-2xl font-bold text-green-900">Payment Successful!</h1>
              <p className="text-green-700 mt-1">You have been enrolled in all purchased courses and your receipt is ready.</p>
            </div>
          </div>
        </div>

        {/* Receipt */}
        <div className="bg-white rounded-lg shadow-lg p-8 print:shadow-none">
          {/* Header */}
          <div className="border-b-2 border-gray-300 pb-6 mb-6">
            <div className="text-center mb-6">
              <h2 className="text-3xl font-bold text-blue-600">PAYMENT RECEIPT</h2>
              <p className="text-gray-600 mt-2">Prem MCX Training Academy</p>
            </div>

            <div className="grid grid-cols-2 gap-8">
              <div>
                <p className="text-sm text-gray-600">Order ID</p>
                <p className="text-lg font-mono font-bold text-gray-900">{receiptData.orderId}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Payment ID</p>
                <p className="text-lg font-mono font-bold text-gray-900">{receiptData.paymentId}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Date & Time</p>
                <p className="text-lg font-bold text-gray-900">{receiptData.date}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Status</p>
                <p className="text-lg font-bold text-green-600">✓ {receiptData.status.toUpperCase()}</p>
              </div>
            </div>
          </div>

          {/* Payer Info */}
          <div className="mb-8 pb-6 border-b border-gray-200">
            <h3 className="text-lg font-bold text-gray-900 mb-4">Payer Information</h3>
            <div className="grid grid-cols-2 gap-8">
              <div>
                <p className="text-sm text-gray-600">Name</p>
                <p className="text-gray-900 font-semibold">{receiptData.userName}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Email</p>
                <p className="text-gray-900 font-semibold">{receiptData.userEmail}</p>
              </div>
            </div>
          </div>

          {/* Courses */}
          <div className="mb-8 pb-6 border-b border-gray-200">
            <h3 className="text-lg font-bold text-gray-900 mb-4">Enrolled Courses</h3>
            <div className="space-y-3">
              {receiptData.courses.map((course, idx) => (
                <div key={idx} className="flex justify-between items-center p-3 bg-gray-50 rounded">
                  <div>
                    <p className="font-semibold text-gray-900">{course.name}</p>
                    <p className="text-sm text-gray-600">Course ID: {course.id}</p>
                  </div>
                  <p className="font-bold text-gray-900">₹{course.price.toLocaleString('en-IN')}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Payment Breakdown */}
          <div className="mb-8 pb-6 border-b border-gray-200">
            <h3 className="text-lg font-bold text-gray-900 mb-4">Payment Breakdown</h3>
            <div className="space-y-3">
              <div className="flex justify-between text-gray-700">
                <span>Subtotal:</span>
                <span className="font-semibold">₹{receiptData.subtotal.toLocaleString('en-IN')}</span>
              </div>
              <div className="flex justify-between text-gray-700">
                <span>SGST (9%):</span>
                <span className="font-semibold">₹{(receiptData.subtotal * 0.09).toLocaleString('en-IN', { maximumFractionDigits: 0 })}</span>
              </div>
              <div className="flex justify-between text-gray-700">
                <span>CGST (9%):</span>
                <span className="font-semibold">₹{(receiptData.subtotal * 0.09).toLocaleString('en-IN', { maximumFractionDigits: 0 })}</span>
              </div>
              <div className="flex justify-between font-bold text-blue-600">
                <span>Total GST (18%):</span>
                <span>₹{receiptData.gst.toLocaleString('en-IN')}</span>
              </div>
            </div>

            <div className="mt-6 pt-6 border-t-2 border-gray-300">
              <div className="flex justify-between items-center">
                <span className="text-xl font-bold text-gray-900">Total Amount Paid:</span>
                <span className="text-3xl font-bold text-green-600">₹{receiptData.total.toLocaleString('en-IN')}</span>
              </div>
            </div>
          </div>

          {/* Notes */}
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <p className="text-sm text-blue-900 font-medium mb-2">✓ Payment Verified with Razorpay</p>
            <p className="text-sm text-blue-900">✓ Instant enrollment in all purchased courses</p>
            <p className="text-sm text-blue-900">✓ You can access courses immediately in "My Courses"</p>
          </div>

          {/* Footer */}
          <div className="mt-8 pt-6 border-t border-gray-200 text-center text-sm text-gray-600">
            <p>For assistance or queries, contact support@premmcxtraining.com</p>
            <p className="mt-2">Receipt generated on {receiptData.date}</p>
          </div>
        </div>

        {/* Actions */}
        <div className="mt-8 flex gap-4 justify-center print:hidden">
          <button
            onClick={printReceipt}
            className="px-6 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition flex items-center gap-2"
          >
            <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4H9a2 2 0 00-2 2v2a2 2 0 002 2h10a2 2 0 002-2v-2a2 2 0 00-2-2h-2m-4-4V9m0 4v4" />
            </svg>
            Print Receipt
          </button>
          <button
            onClick={downloadReceipt}
            className="px-6 py-3 bg-green-600 text-white rounded-lg font-semibold hover:bg-green-700 transition flex items-center gap-2"
          >
            <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download Receipt
          </button>
          <Link
            href="/my-courses"
            className="px-6 py-3 bg-gray-600 text-white rounded-lg font-semibold hover:bg-gray-700 transition flex items-center gap-2"
          >
            <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
            </svg>
            Go to My Courses
          </Link>
        </div>
      </div>
    </div>
  );
}

export default function PaymentReceiptPage() {
  return (
    <Suspense fallback={<div>Loading receipt...</div>}>
      <PaymentReceiptContent />
    </Suspense>
  );
}
